[2019-02-05T13:03:52.386] [FATAL] index - no se pudo conectar a la base de datos,revise la conexion al servidor
[2019-02-05T14:23:01.821] [FATAL] index - no se pudo conectar a la base de datos,revise la conexion al servidor { MongoNetworkError: failed to connect to server [ds161104.mlab.com:61104] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND ds161104.mlab.com ds161104.mlab.com:61104]
    at Pool.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:188:13)
    at Connection.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:276:13)
    at Connection.emit (events.js:188:13)
    at Socket.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:276:13)
    at Socket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
[2019-03-18T14:52:49.490] [FATAL] index - no se pudo conectar a la base de datos,revise la conexion al servidor { MongoNetworkError: failed to connect to server [ds161104.mlab.com:61104] on first connect [MongoNetworkError: connect ETIMEDOUT 3.86.67.227:61104]
    at Pool.<anonymous> (E:\Development\Interact\motelMovil\ServerNode\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:188:13)
    at Connection.<anonymous> (E:\Development\Interact\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:276:13)
    at Connection.emit (events.js:188:13)
    at Socket.<anonymous> (E:\Development\Interact\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:276:13)
    at Socket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
[2019-03-18T14:54:04.006] [FATAL] index - no se pudo conectar a la base de datos,revise la conexion al servidor { MongoNetworkError: failed to connect to server [ds161104.mlab.com:61104] on first connect [MongoNetworkError: connect ETIMEDOUT 3.86.67.227:61104]
    at Pool.<anonymous> (E:\Development\Interact\motelMovil\ServerNode\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:188:13)
    at Connection.<anonymous> (E:\Development\Interact\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:276:13)
    at Connection.emit (events.js:188:13)
    at Socket.<anonymous> (E:\Development\Interact\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:276:13)
    at Socket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
[2019-03-20T08:28:01.399] [FATAL] index - no se pudo conectar a la base de datos,revise la conexion al servidor { MongoNetworkError: failed to connect to server [192.168.1.14:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 192.168.1.14:27017]
    at Pool.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:188:13)
    at Connection.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:276:13)
    at Connection.emit (events.js:188:13)
    at Socket.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:276:13)
    at Socket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
[2019-03-20T09:10:19.950] [FATAL] index - no se pudo conectar a la base de datos,revise la conexion al servidor { MongoNetworkError: failed to connect to server [ds161104.mlab.com:61104] on first connect [MongoNetworkError: connect ETIMEDOUT 3.86.67.227:61104]
    at Pool.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:188:13)
    at Connection.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:276:13)
    at Connection.emit (events.js:188:13)
    at Socket.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:276:13)
    at Socket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
[2019-03-20T09:13:00.149] [FATAL] index - no se pudo conectar a la base de datos,revise la conexion al servidor { MongoNetworkError: failed to connect to server [ds161104.mlab.com:61104] on first connect [MongoNetworkError: connect ETIMEDOUT 3.86.67.227:61104]
    at Pool.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:188:13)
    at Connection.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:276:13)
    at Connection.emit (events.js:188:13)
    at Socket.<anonymous> (F:\Gamboa corporation\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\connection.js:246:50)
[2019-03-20T09:12:46.833] [FATAL] index - no se pudo conectar a la base de datos,revise la conexion al servidor { MongoNetworkError: failed to connect to server [ds161104.mlab.com:61104] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND ds161104.mlab.com ds161104.mlab.com:61104]
    at Pool.<anonymous> (E:\Development\Interact\motelMovil\ServerNode\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:188:13)
    at Connection.<anonymous> (E:\Development\Interact\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:276:13)
    at Connection.emit (events.js:188:13)
    at Socket.<anonymous> (E:\Development\Interact\motelMovil\ServerNode\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:276:13)
    at Socket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
